name: simdart_examples
description: Examples of SimDart.
version: 0.1.0
repository: https://github.com/SimDart/simdart-examples

environment:
  sdk: ^3.6.0

dependencies:
  simdart: #^0.1.0
    path: ../simdart

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
